[tools]
node = "26.4.0"
pnpm = "11.9.0"

[tasks.check]
description = "全てのコマンドをチェックする"
run = [
  "pnpm run typecheck",
  "pnpm run format",
  "pnpm run lint",
  "pnpm run test:coverage",
  "pnpm run build"
]
